discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
discord.client - INFO - logging in using static token
discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 46c6ee6cc4844eff8c794f3648f7a2ce).
root - INFO - returning message
root - INFO - await to get response
discord.gateway - WARNING - Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\wist2\AppData\Local\Programs\Python\Python311\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\wist2\AppData\Local\Programs\Python\Python311\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "c:\Users\wist2\.vscode\extensions\ms-python.python-2023.20.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\wist2\.vscode\extensions\ms-python.python-2023.20.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\wist2\.vscode\extensions\ms-python.python-2023.20.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\wist2\.vscode\extensions\ms-python.python-2023.20.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\wist2\.vscode\extensions\ms-python.python-2023.20.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\wist2\.vscode\extensions\ms-python.python-2023.20.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "C:\Users\wist2\Univ\Education\팀프로젝트1\프로젝트2\leader_gpt\discord_bot.py", line 87, in <module>
    client.run(BOT_TOKEN)
  File "C:\Users\wist2\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\wist2\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\wist2\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\wist2\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\wist2\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\wist2\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\wist2\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\wist2\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\wist2\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\wist2\Univ\Education\팀프로젝트1\프로젝트2\leader_gpt\discord_bot.py", line 31, in on_message
    await self.answer(message)            # answer to command
  File "C:\Users\wist2\Univ\Education\팀프로젝트1\프로젝트2\leader_gpt\discord_bot.py", line 39, in answer
    await self.command_keywords[keyword](message)
  File "C:\Users\wist2\Univ\Education\팀프로젝트1\프로젝트2\leader_gpt\discord_bot.py", line 79, in gpt4_answer
    answer = chatgpt.get_response(content, model=chatgpt.gpt_model['gpt4'])
  File "C:\Users\wist2\Univ\Education\팀프로젝트1\프로젝트2\leader_gpt\chatgpt.py", line 34, in get_response
    return get_response_object(message, model=model, user=user).choices[0].message.content
  File "C:\Users\wist2\Univ\Education\팀프로젝트1\프로젝트2\leader_gpt\chatgpt.py", line 22, in get_response_object
    response = openai.ChatCompletion.create(
  File "C:\Users\wist2\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\wist2\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
  File "C:\Users\wist2\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 289, in request
    result = self.request_raw(
  File "C:\Users\wist2\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 606, in request_raw
    result = _thread_context.session.request(
  File "C:\Users\wist2\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\wist2\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\wist2\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\wist2\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "C:\Users\wist2\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "C:\Users\wist2\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "C:\Users\wist2\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1378, in getresponse
    response.begin()
  File "C:\Users\wist2\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\wist2\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\wist2\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 706, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\wist2\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1311, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\wist2\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1167, in read
    return self._sslobj.read(len, buffer)

root - INFO - gettnig token usage
root - INFO - token increased
